freebsd_instance:
  image_family: freebsd-13-0

build_task:
  env:
    PATH: ${HOME}/.cargo/bin:${PATH}
  install_script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  check_script: cargo clippy
  build_script: cargo build --release
  list_script: ls target/release
  binaries_artifacts:
    path: target/release/lib*

deploy_task:
  depends_on: 
    - build
  env:
    GITHUB_TOKEN: ENCRYPTED[qwerty]
  script: |
    ls target/release
    echo "Deploy using $ENCRYPTED"
