freebsd_instance:
  image_family: freebsd-13-0

build_task:
  env:
    PATH: ${HOME}/.cargo/bin:${PATH}
  install_script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  check_script: cargo clippy
  build_script: cargo build --release
  package_script: |
    cd plugins
    cp ../target/release/*.so ./
    for f in *.so; do
      mv "$f" "${f#lib}"
    done
    cd ..
    tar -czvf collectd-plugins.tar.gz plugins/ ./debug.conf ./README.md
  artifacts:
    path: collectd-plugins.tar.gz
