freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script: |
    pkg install -y curl
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    export PATH="$HOME/.cargo/bin:$PATH"
  check_script: $HOME/.cargo/bin/cargo clippy
  build_script: $HOME/.cargo/bin/cargo build --release
