freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script: |
    pkg install -y curl
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    source $HOME/.cargo/env
  script: |
    cargo clippy
    cargo build --release
